# Generated by Django 3.2.16 on 2023-01-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
