# Generated by Django 3.2.16 on 2023-01-12 22:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0002_anime_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='anime_title'),
        ),
    ]
