# Generated by Django 3.2.16 on 2023-02-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
